env: "gymma"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 100
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 50000
