env: simcity

env_args:
  key: "simcity"
  map_name: "simcity"
  seed: null
  time_limit: 100
  grid_size: 4

test_greedy: True
test_nepisode: 20
test_interval: 2
log_interval: 2
runner_log_interval: 2
learner_log_interval: 2
t_max: 3
