env: simcity

env_args:
  key: "simcity"
  map_name: "simcity"
  seed: null
  time_limit: 100
  grid_size: 4

test_greedy: True
test_nepisode: 20
test_interval: 100
log_interval: 100
runner_log_interval: 100
learner_log_interval: 100
t_max: 3
