env: simcity

env_args:
  key: "simcity"
  map_name: "simcity"
  seed: null
  time_limit: 100
  grid_x: 4
  grid_y: 4

test_greedy: True
test_nepisode: 20
test_interval: 100
log_interval: 100
runner_log_interval: 100
learner_log_interval: 100
t_max: 1000
common_reward: True
use_tensorboard: True
use_cuda: True
save_model: True # Save the models to disk
save_model_interval: 1000 # Save models after this many timesteps